name: input_quantity
description: A widget for input quantity. Built with TextFormField. Type manually or increase and decrease value with the btn

version: 1.2.4

# homepage: https://pmatatias.dev
repository: https://github.com/pmatatias/input-quantity
issue_tracker: https://github.com/pmatatias/input-quantity/issues

environment:
  sdk: ">=2.17.3 <4.0.0"
  flutter: ">=1.17.0"

funding:
  - https://www.buymeacoffee.com/pmatatias

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

screenshots:
  - description: "Demo input quantity"
    path: assets/DEMO.gif
